# Generated by Django 5.2.17 on 2026-09-29 00:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloFinanceiro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('RECEBER', 'A receber'), ('PAGAR', 'A pagar')], max_length=10)),
                ('descricao', models.CharField(max_length=180)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PAGO', 'Pago/recebido'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=16)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulos_a_receber', to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulos_a_pagar', to='core.fornecedor')),
            ],
            options={
                'verbose_name': 'título financeiro',
                'verbose_name_plural': 'títulos financeiros',
                'ordering': ['vencimento', 'descricao'],
            },
        ),
    ]
